### ISSUE TITLE
Fix our goal structure

### ISSUE THREAD

**Issue by jzoon** [spiderbiggen/RAMpestampers-Context-VH#56]
At this point, our structure on adopting goals is kind of ugly, we can improve this code.

**Comment by tvleest** [comment]
getIndicatorGoals :- false.

**Comment by tvleest** [comment]
I tried putting it in the init module so this goal wasn't neccessary. But it didn't work before since adoption of goals isn't allowed in the init module (At least is suspect that this is the problem), but I'll see if I can come up with a cleaner solution.

**Comment by tvleest** [comment]
#58 Should fix this.

**Comment by spiderbiggen** [comment]
#60 Should fix this.

**Comment by spiderbiggen** [comment]
This should be fixed now
